package com.yeswanth.expensetrackerapi.repository;

import com.yeswanth.expensetrackerapi.models.Expense;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.util.Date;

@Repository
public interface ExpenseRepository extends JpaRepository<Expense, Long> {

    //select * from tbl_expenses where category=?
    Page<Expense> findByCategory(String category, Pageable page);

    /*this query will be generated by jpa automatically because we used keyword containing
     select * from tbl_expense where name LIKE '%keyword*'; */
    Page<Expense> findByNameContaining(String keyword, Pageable page);

    //select * from tbl_expense where date between 'startDate' AND 'endDate';
    Page<Expense> findByDateBetween(Date startDate, Date endDate, Pageable page);

}
